version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "3001:3001"
    networks:
      - app-network
    environment:
      - NODE_ENV=production
      - NODE_OPTIONS=--dns-result-order=ipv4first

  frontend:
    build:
      context: ./frontend
    ports:
      - "4200:4200"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
    enable_ipv6: false 
    ipam:
      config:
        - subnet: 172.20.0.0/16
          gateway: 172.20.0.1